### PR TITLE
endOfLine: "lf" option in tests/standard

### PR DESCRIPTION
**Pull request by brody2consult**
(tests/standard/jsfmt.spec.js)

as proposed by @aMarCruz in PR #46, now moved into its own PR

/cc @aMarCruz

### CODE REVIEW

**Comment by aMarCruz** [comment]
Great.

**Comment by brody2consult** [comment]
Hey @aMarCruz what was the motivation?

I am ready to merge it, just curious.

**Comment by aMarCruz** [comment]
Sorry, this also comes from my own configu. t's a habit, in the past I had problems with commits from Windows platforms.

**Comment by brody2consult** [comment]
OK. I'm gonna keep it for now, at least. Consistent across all platforms.

**Comment by aMarCruz** [comment]
Thanks

**Pull request merged**
